name: animated_vector
description: A package that adds support for vector data based animations.
version: 0.2.2
homepage: https://github.com/HrX03/animated_vector/tree/main/packages/animated_vector_annotations
repository: https://github.com/HrX03/animated_vector
license: MIT
screenshots:
  - description: "animated_vector library logo, it's made up of a square in the bottom left corner with a 'V' on it and a circle on the top right corner with an 'A' on it"
    path: "static/logo_pub.gif"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter

  image: ^4.10.1
  path_parsing: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lint: ^2.14.0

flutter:
